[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd frontend/stackhabit-app && npm ci"]

[phases.build]
cmds = ["cd frontend/stackhabit-app && npm run build"]

[start]
cmd = "cd frontend/stackhabit-app && npm run preview"

