[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore StackHabit.API/StackHabit.API.csproj"]

[phases.build]
cmds = ["dotnet publish StackHabit.API/StackHabit.API.csproj --configuration Release --no-restore -o StackHabit.API/out"]

[start]
cmd = "./StackHabit.API/out/StackHabit.API --urls http://0.0.0.0:$PORT"

