[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet build --configuration Release --no-restore"]

[start]
cmd = "dotnet run --no-build --urls http://0.0.0.0:$PORT"

