[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore StackHabit.API.csproj"]

[phases.build]
cmds = ["dotnet publish StackHabit.API.csproj --configuration Release --no-restore -o out"]

[start]
cmd = "./out/StackHabit.API --urls http://0.0.0.0:$PORT"

